In [ ]:
import pandas as pd
df = pd.read_json('/content/drive/MyDrive/business_joined.json')
df.head()

_id                   address  \
0  {'$oid': '63fe89f0d60a9a69b84f365a'}  2001 Piazza Ave, Ste 100   
1  {'$oid': '63fe89f0d60a9a69b84f365b'}  2001 Piazza Ave, Ste 100   
2  {'$oid': '63fe89f0d60a9a69b84f365c'}  2001 Piazza Ave, Ste 100   
3  {'$oid': '63fe89f0d60a9a69b84f365d'}  2001 Piazza Ave, Ste 100   
4  {'$oid': '63fe89f0d60a9a69b84f365e'}  2001 Piazza Ave, Ste 100   

              business_id           city  is_open   latitude  longitude  \
0  -I8rPwW2mH-pxMeyk22f7g  Wesley Chapel        0  28.189038 -82.347692   
1  -I8rPwW2mH-pxMeyk22f7g  Wesley Chapel        0  28.189038 -82.347692   
2  -I8rPwW2mH-pxMeyk22f7g  Wesley Chapel        0  28.189038 -82.347692   
3  -I8rPwW2mH-pxMeyk22f7g  Wesley Chapel        0  28.189038 -82.347692   
4  -I8rPwW2mH-pxMeyk22f7g  Wesley Chapel        0  28.189038 -82.347692   

                 name  postal_code  review_count  ...   Alcohol DriveThru  \
0  Pagelli's Italiano        33543            13  ...  full_bar     False   
1  Pagelli's Italiano        33543            13  ...  full_bar     False   
2  Pagelli's Italiano        33543            13  ...  full_bar     False   
3  Pagelli's Italiano        33543            13  ...  full_bar     False   
4  Pagelli's Italiano        33543            13  ...  full_bar     False   

  Categories cool                date funny               review_id stars  \
0    Italian    2 2012-06-26 18:31:16     1  Mgw2Tzea5quFVwBQL1OFYA     4   
1    Italian    1 2011-12-02 14:05:58     1  8sOaDBSRKSMvvgd-FF7-cQ     3   
2    Italian    0 2011-04-26 03:15:09     0  a00WNmUzoFv4jlJ7qHsnbQ     4   
3    Italian    0 2011-10-02 02:20:39     0  BZXl-NZ2zkah2Q_7E6RDkg     4   
4    Italian    0 2011-11-06 00:51:34     0  nAeVYBEmx1Xf5EXxRo1fKA     1   

                                                text useful  
0  I think its funny when people bitch that there...      3  
1  My wife and I just had our second child, and w...      3  
2  I eat at pagelli's italiano for the first time...      0  
3  Went here for the early dinner special before ...      0  
4  Went for dinner, and never even got our food. ...      2  

[5 rows x 33 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#importing all the required libraries
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.stem import WordNetLemmatizer
from nltk import tokenize

In [ ]:
df = df[['text','stars']]

In [ ]:
df['target'] = ""
df.loc[df['stars'] >=3.5,'target'] = 'pos'
df.loc[df['stars'] <=2.5,'target'] = 'neg'

<ipython-input-5-8174c047563c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'] = ""
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [ ]:
df = df.loc[df['target'] !=""]

In [ ]:
df

text  stars target
0       I think its funny when people bitch that there...      4    pos
2       I eat at pagelli's italiano for the first time...      4    pos
3       Went here for the early dinner special before ...      4    pos
4       Went for dinner, and never even got our food. ...      1    neg
6       The Fettuccine Alfredo is fantastic at Pagelli...      4    pos
...                                                   ...    ...    ...
497879  I drive by this everyday so I decided to try i...      2    neg
497880  Last night a friend and l went to gyros on 34t...      1    neg
497881  As expensive as they are, I was hoping for a g...      1    neg
497882  Ok. My gyro was loaded with meat and it was co...      4    pos
497883  Worst Customer Service I've ever encountered! ...      1    neg

[443834 rows x 3 columns]

In [ ]:
train_dataset = df.sample(100000)
test_dataset = df.sample(10000)

In [ ]:
train_dataset = train_dataset.reset_index()
train_dataset = train_dataset.rename(columns={'index':'rem'})
train_dataset.drop("rem",axis=1,inplace=True)
test_dataset = test_dataset.reset_index()
test_dataset =test_dataset.rename(columns={'index':'rem'})
test_dataset.drop("rem",axis=1,inplace=True)

In [ ]:
train_dataset.drop("stars",axis=1,inplace=True)
test_dataset.drop("stars",axis=1,inplace=True)

In [ ]:
df = train_dataset

In [ ]:
df = df.rename(columns={"text":"review"})
df

review target
0      Well here it is, September 11th and still no S...    neg
1      This is a neat place to come for a drink and a...    pos
2      Tonight they earned a 1 star as I would have s...    neg
3      Great service\nGood food\nConvenient location,...    pos
4      What a find!  Beautiful inside and the service...    pos
...                                                  ...    ...
99995  Ale House is really a great sports bar and the...    pos
99996  Excellent Pho and Bun - get the lemongrass hon...    pos
99997  Amazing place! The atmosphere was great and th...    pos
99998  Went there with my family Tuesday. First time ...    pos
99999  Absolutely ridiculous that ruby Tuesday's prom...    neg

[100000 rows x 2 columns]

In [ ]:
#converting the reviews into lower case
df.review=df.review.apply(lambda x: x.lower())
df

review target
0      well here it is, september 11th and still no s...    neg
1      this is a neat place to come for a drink and a...    pos
2      tonight they earned a 1 star as i would have s...    neg
3      great service\ngood food\nconvenient location,...    pos
4      what a find!  beautiful inside and the service...    pos
...                                                  ...    ...
99995  ale house is really a great sports bar and the...    pos
99996  excellent pho and bun - get the lemongrass hon...    pos
99997  amazing place! the atmosphere was great and th...    pos
99998  went there with my family tuesday. first time ...    pos
99999  absolutely ridiculous that ruby tuesday's prom...    neg

[100000 rows x 2 columns]

In [ ]:
!pip install contractions

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import contractions

In [ ]:
# Expanding contractions
def con(text):
  expand=contractions.fix(text)
  return expand

df.review=df.review.apply(con)
df['review'][0]

'well here it is, september 11th and still no september update of the live music at the spa on the website, just like last month. this happens every month, management is very lackadaisical about updating information. a while back they had a musical duet in the ballroom and i called to see when it was happening. the desk said no entertainment that night. i stopped by later just to make sure and there was the line of people going into the ballroom for the concert. the ballroom was literally across the hallway from the front desk, across...the...hallway!  management makes sure communication is kept at a minimum, making it a point to keep the public and their employees in the dark. employees take up the slack by turning a blind eye to the obvious line forming for the ballroom event....if you order something to eat at the pool be ready to cool your heals at least and hour, welcome to the slowest service of all time!  the spa should get rid of the management team and start for scratch . exis

In [ ]:
import re

def remove_sp(text):
  pattern=r'[^A-Za-z0-9\s]'
  text=re.sub(pattern,'',text)
  return text

df.review=df.review.apply(remove_sp)
df

review target
0      well here it is september 11th and still no se...    neg
1      this is a neat place to come for a drink and a...    pos
2      tonight they earned a 1 star as i would have s...    neg
3      great service\ngood food\nconvenient location ...    pos
4      what a find  beautiful inside and the service ...    pos
...                                                  ...    ...
99995  ale house is really a great sports bar and the...    pos
99996  excellent pho and bun  get the lemongrass hone...    pos
99997  amazing place the atmosphere was great and the...    pos
99998  went there with my family tuesday first time t...    pos
99999  absolutely ridiculous that ruby tuesdays promo...    neg

[100000 rows x 2 columns]

In [ ]:
import string
punctuations=list(string.punctuation)

In [ ]:
df.review=df.review.apply(lambda x : " ".join(x for x in x.split() if x not in punctuations))

In [ ]:
# Removing stopwords
nltk.download('stopwords')
stopword_list=stopwords.words('english')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
stopword_list.remove('no')
stopword_list.remove('not')


In [ ]:
df.review=df.review.apply(lambda x : " ".join(x for x in x.split() if x not in stopword_list))
df['review'][5]

'go spot looking something quick delicious still sit restaurant menu enough variety please everyone not overwhelming portion sizes small side hungry offer large portion get dad cesar salad entree tiny portion would considered appetizer sized always get salmon salad comes really tasty goat cheese croquet also love chick pea fries cauliflower spinach dip great happy hour specials every day week nice big parking lot front not sure carrollwood even peak lunch time week dinner weekend never wait table also ipad order server mia club caramel card gives rewards already earned 20 definitely one regular spots'

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
df['review']=df.review.apply(word_tokenize)
df['review'][0]


['well',
 'september',
 '11th',
 'still',
 'no',
 'september',
 'update',
 'live',
 'music',
 'spa',
 'website',
 'like',
 'last',
 'month',
 'happens',
 'every',
 'month',
 'management',
 'lackadaisical',
 'updating',
 'information',
 'back',
 'musical',
 'duet',
 'ballroom',
 'called',
 'see',
 'happening',
 'desk',
 'said',
 'no',
 'entertainment',
 'night',
 'stopped',
 'later',
 'make',
 'sure',
 'line',
 'people',
 'going',
 'ballroom',
 'concert',
 'ballroom',
 'literally',
 'across',
 'hallway',
 'front',
 'desk',
 'acrossthehallway',
 'management',
 'makes',
 'sure',
 'communication',
 'kept',
 'minimum',
 'making',
 'point',
 'keep',
 'public',
 'employees',
 'dark',
 'employees',
 'take',
 'slack',
 'turning',
 'blind',
 'eye',
 'obvious',
 'line',
 'forming',
 'ballroom',
 'eventif',
 'order',
 'something',
 'eat',
 'pool',
 'ready',
 'cool',
 'heals',
 'least',
 'hour',
 'welcome',
 'slowest',
 'service',
 'time',
 'spa',
 'get',
 'rid',
 'management',
 'team',
 'start',
 

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
lemmatizer=WordNetLemmatizer()


In [ ]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [ ]:
df['review']=df.review.apply(lambda x:[lemmatizer.lemmatize(word) for word in x])

In [ ]:
df


review target
0      [well, september, 11th, still, no, september, ...    neg
1      [neat, place, come, drink, snack, ambiance, gr...    pos
2      [tonight, earned, 1, star, would, sent, everyt...    neg
3      [great, service, good, food, convenient, locat...    pos
4      [find, beautiful, inside, service, spectacular...    pos
...                                                  ...    ...
99995  [ale, house, really, great, sport, bar, food, ...    pos
99996  [excellent, pho, bun, get, lemongrass, honey, ...    pos
99997  [amazing, place, atmosphere, great, flamenco, ...    pos
99998  [went, family, tuesday, first, time, heard, lo...    pos
99999  [absolutely, ridiculous, ruby, tuesday, promot...    neg

[100000 rows x 2 columns]

In [ ]:


df.review= df.review.astype(str)



In [ ]:
import numpy as np
review_list=df['review'].array
review_list.shape


(100000,)

In [ ]:
df_bin = df
df_bin['target'] = np.where(df['target']=='pos',1,0)

In [ ]:
df_bin

review  target
0      ['well', 'september', '11th', 'still', 'no', '...       0
1      ['neat', 'place', 'come', 'drink', 'snack', 'a...       1
2      ['tonight', 'earned', '1', 'star', 'would', 's...       0
3      ['great', 'service', 'good', 'food', 'convenie...       1
4      ['find', 'beautiful', 'inside', 'service', 'sp...       1
...                                                  ...     ...
99995  ['ale', 'house', 'really', 'great', 'sport', '...       1
99996  ['excellent', 'pho', 'bun', 'get', 'lemongrass...       1
99997  ['amazing', 'place', 'atmosphere', 'great', 'f...       1
99998  ['went', 'family', 'tuesday', 'first', 'time',...       1
99999  ['absolutely', 'ridiculous', 'ruby', 'tuesday'...       0

[100000 rows x 2 columns]

In [ ]:
x = df_bin.iloc[:,0].values
y = df_bin.iloc[:,1].values

In [ ]:
#!pip uninstall scikit-learn -y

#!pip install -U scikit-learn
from sklearn.model_selection import train_test_split
import sklearn
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)

sklearn_version = sklearn.__version__


print(sklearn_version)

1.2.1


In [ ]:
import sklearn
sklearn_version = sklearn.__version__
print(sklearn_version)

1.2.1


In [ ]:
print(x_train.shape)
x_test.shape


(75000,)


(25000,)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
sklearn_version = sklearn.__version__
print(sklearn_version)

1.2.1


In [ ]:
!pip install xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from xgboost import XGBClassifier

In [ ]:
final = Pipeline([('Vect',TfidfVectorizer()),
                  ('model',XGBClassifier())])

In [ ]:
y_train

array([1, 1, 1, ..., 0, 0, 1])

In [ ]:
final.fit(x_train,y_train)


Pipeline(steps=[('Vect', TfidfVectorizer()),
                ('model',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, gpu_id=None,
                               grow_policy=None, importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, n_estimators=100,
                               n_jobs=None, num_parallel_tree=None,
                               predictor=None, random_state=None, ...))])

In [ ]:
y_pred=final.predict(x_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
y_test

array([0, 1, 1, ..., 1, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
sklearn_version = sklearn.__version__
print(sklearn_version)

1.2.1


In [ ]:
accuracy_score(y_test,y_pred)

0.94752

In [ ]:
confusion_matrix(y_test,y_pred)

array([[ 4915,   828],
       [  484, 18773]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.86      0.88      5743
           1       0.96      0.97      0.97     19257

    accuracy                           0.95     25000
   macro avg       0.93      0.92      0.92     25000
weighted avg       0.95      0.95      0.95     25000



In [ ]:
from sklearn.metrics import roc_auc_score

y_pred_proba = final.predict_proba(x_test)[:,1]
print(roc_auc_score(y_test,y_pred_proba))

0.9839241381668168


In [ ]:
df = test_dataset

In [ ]:
df = df.rename(columns={"text":"review"})
df

review target
0     Never go back here again for food.\nWaitress w...    neg
1     Just had lunch there and it was exceptional.  ...    pos
2     Ehhh I guess I was expecting better when I see...    neg
3     So confused by these reviews. Ordered to-go wi...    neg
4     So, we love going to the Cheesecake Factory......    neg
...                                                 ...    ...
9995  We had a great experience! Sarah was our serve...    pos
9996  ***ALERT*** this is the only Taco place that d...    neg
9997  I enjoyed dining at Stella's! The atmosphere w...    pos
9998  food is awesome Kim is best ask for her when y...    pos
9999  Fantastic food and service. Fish tacos are gre...    pos

[10000 rows x 2 columns]

In [ ]:
#converting the reviews into lower case
df.review=df.review.apply(lambda x: x.lower())
df

review target
0     never go back here again for food.\nwaitress w...    neg
1     just had lunch there and it was exceptional.  ...    pos
2     ehhh i guess i was expecting better when i see...    neg
3     so confused by these reviews. ordered to-go wi...    neg
4     so, we love going to the cheesecake factory......    neg
...                                                 ...    ...
9995  we had a great experience! sarah was our serve...    pos
9996  ***alert*** this is the only taco place that d...    neg
9997  i enjoyed dining at stella's! the atmosphere w...    pos
9998  food is awesome kim is best ask for her when y...    pos
9999  fantastic food and service. fish tacos are gre...    pos

[10000 rows x 2 columns]

In [ ]:
# Expanding contractions
def con(text):
  expand=contractions.fix(text)
  return expand

df.review=df.review.apply(con)
df['review'][0]

'never go back here again for food.\nwaitress was simply the worst, and overall experience was lame. \nthis place is not for me, but hey...maybe its for you...\ni know my partner loved the prime rib sandwich.\nmaybe a great place for the guys....'

In [ ]:
import re

def remove_sp(text):
  pattern=r'[^A-Za-z0-9\s]'
  text=re.sub(pattern,'',text)
  return text

df.review=df.review.apply(remove_sp)
df

review target
0     never go back here again for food\nwaitress wa...    neg
1     just had lunch there and it was exceptional  b...    pos
2     ehhh i guess i was expecting better when i see...    neg
3     so confused by these reviews ordered togo with...    neg
4     so we love going to the cheesecake factoryhowe...    neg
...                                                 ...    ...
9995  we had a great experience sarah was our server...    pos
9996  alert this is the only taco place that does no...    neg
9997  i enjoyed dining at stellas the atmosphere was...    pos
9998  food is awesome kim is best ask for her when y...    pos
9999  fantastic food and service fish tacos are grea...    pos

[10000 rows x 2 columns]

In [ ]:
import string
punctuations=list(string.punctuation)

In [ ]:
df.review=df.review.apply(lambda x : " ".join(x for x in x.split() if x not in punctuations))

In [ ]:
# Removing stopwords
nltk.download('stopwords')
stopword_list=stopwords.words('english')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
stopword_list.remove('no')
stopword_list.remove('not')


In [ ]:
df.review=df.review.apply(lambda x : " ".join(x for x in x.split() if x not in stopword_list))
df['review'][5]

'favorite place tampa healthy fast tasty nice wish bit bigger interior always able find table'

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
df['review']=df.review.apply(word_tokenize)
df['review'][0]


['never',
 'go',
 'back',
 'food',
 'waitress',
 'simply',
 'worst',
 'overall',
 'experience',
 'lame',
 'place',
 'not',
 'heymaybe',
 'know',
 'partner',
 'loved',
 'prime',
 'rib',
 'sandwich',
 'maybe',
 'great',
 'place',
 'guys']

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
lemmatizer=WordNetLemmatizer()


In [ ]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [ ]:
df['review']=df.review.apply(lambda x:[lemmatizer.lemmatize(word) for word in x])

In [ ]:
df


review target
0     [never, go, back, food, waitress, simply, wors...    neg
1     [lunch, exceptional, beer, cold, shrimp, fish,...    pos
2     [ehhh, guess, expecting, better, seen, air, fr...    neg
3     [confused, review, ordered, togo, 3, girlfrien...    neg
4     [love, going, cheesecake, factoryhowever, not,...    neg
...                                                 ...    ...
9995  [great, experience, sarah, server, attentive, ...    pos
9996  [alert, taco, place, nothing, taco, tuesday, k...    neg
9997  [enjoyed, dining, stella, atmosphere, great, a...    pos
9998  [food, awesome, kim, best, ask, go, get, octop...    pos
9999  [fantastic, food, service, fish, taco, great, ...    pos

[10000 rows x 2 columns]

In [ ]:


df.review= df.review.astype(str)



In [ ]:
import numpy as np
review_list=df['review'].array
review_list.shape


(10000,)

In [ ]:
df_bin = df
df_bin['target'] = np.where(df['target']=='pos',1,0)

In [ ]:
df_bin

review  target
0     ['never', 'go', 'back', 'food', 'waitress', 's...       0
1     ['lunch', 'exceptional', 'beer', 'cold', 'shri...       1
2     ['ehhh', 'guess', 'expecting', 'better', 'seen...       0
3     ['confused', 'review', 'ordered', 'togo', '3',...       0
4     ['love', 'going', 'cheesecake', 'factoryhoweve...       0
...                                                 ...     ...
9995  ['great', 'experience', 'sarah', 'server', 'at...       1
9996  ['alert', 'taco', 'place', 'nothing', 'taco', ...       0
9997  ['enjoyed', 'dining', 'stella', 'atmosphere', ...       1
9998  ['food', 'awesome', 'kim', 'best', 'ask', 'go'...       1
9999  ['fantastic', 'food', 'service', 'fish', 'taco...       1

[10000 rows x 2 columns]

In [ ]:
x_val = df_bin.iloc[:,0].values
y_val = df_bin.iloc[:,1].values

In [ ]:
y_pred=final.predict(x_val)
y_pred

array([1, 1, 0, ..., 1, 1, 1])

In [ ]:
accuracy_score(y_val,y_pred)

0.9526

In [ ]:
confusion_matrix(y_val,y_pred)

array([[2091,  317],
       [ 157, 7435]])

In [ ]:
print(classification_report(y_val,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.87      0.90      2408
           1       0.96      0.98      0.97      7592

    accuracy                           0.95     10000
   macro avg       0.94      0.92      0.93     10000
weighted avg       0.95      0.95      0.95     10000



In [ ]:
from sklearn.metrics import roc_auc_score

y_pred_proba = final.predict_proba(x_test)[:,1]
print(roc_auc_score(y_val,y_pred_proba))

0.9852984453822698


In [ ]:
x_val[1]

"['lunch', 'exceptional', 'beer', 'cold', 'shrimp', 'fish', 'blackened', 'taco', 'platterfish', 'taco', 'crazy', 'good', 'shrimp', 'really', 'good', 'lost', 'nose', 'great', 'atmosphere', 'hair', 'quieter', 'local', 'place', 'block', 'mandalay', 'take', 'time', 'stop', 'staff', 'super', 'friendly', 'kitchen', 'area', 'really', 'clean', 'also', 'mention', 'boy', 'twice', 'afternoon', 'milkshake', 'reasonably', 'priced', 'really', 'good', 'per', 'teenage', 'son', 'younger', 'brother']"

In [ ]:
final.predict([x_val[1]])

array([1])

In [ ]:
x_val[3]

"['confused', 'review', 'ordered', 'togo', '3', 'girlfriend', '1pm', 'sunday', 'woman', 'phone', 'short', 'rude', 'seemed', 'bothered', 'getting', 'business', 'said', 'would', 'take', '25', 'minute', '4', 'sandwich', '25', 'minute', 'later', 'show', 'upthe', 'place', 'empty', 'no', 'light', 'come', 'inside', 'pay', 'wait', '15', 'minute', 'foodso', 'total', '40', 'minute', '4', 'sandwich', 'walk', 'back', 'place', '14', 'mile', 'start', 'eating', 'sandwich', 'disgusting', 'mean', 'wow', 'prosciutto', 'artichoke', 'sandwich', 'inedible', 'salty', 'literally', 'could', 'not', 'eat', 'bread', 'stale', 'would', 'not', 'break', 'ham', 'hard', 'like', 'plastic', 'artichoke', 'tasted', 'like', 'gone', 'bad', 'friend', 'meal', 'equally', 'disgusting', 'looked', 'shock', 'bad', 'food', 'honestly', 'think', 'bad', 'sandwich', 'night', 'semi', 'reheated', 'served', 'u', 'can', 'not', 'believe', 'place', 'served', 'u', 'food', 'like', 'total', 'spent', '40', 'thought', 'complaining', 'not', 'want'

In [ ]:
final.predict([x_test[3]])

array([0])

In [ ]:
x_val[47]

"['tampa', 'greatest', 'upscale', 'deli', 'say', 'least', 'love', 'thank', 'great', 'experience', 'every', 'time', 'clarissa', 'mitch', 'south', 'tampa']"

In [ ]:
final.predict([x_test[17]])

array([1])

In [ ]:
import pickle
pickle.dump(final,open('sentiment_analysis_model.p','wb'))

In [ ]:
message = test_dataset.sample(1)['text']

In [ ]:
message = message[3017]


In [ ]:
message

"Wow what a good place! I had the turkey club with a scoop of the fancy Nancy and I had the turkey club on a croissant.\n\nSo the fancy Nancy is a scoop of their chicken salad and it's listed under their fruity and nutty selection.  It has Fuji apples seedless grapes and pecans and a scoop is only 390 calories.\n\n\nEverything was excellent and the service was fantastic. I can't wait to go back!"

In [ ]:
message ="This restaurant is so bad.I will never visit it again. I ddi not enjoy this place even though some aspects were all right"

In [ ]:
model=pickle.load(open('sentiment_analysis_model.p','rb'))
a=model.predict([message])[0]
if(a==1):
  disp = "Positive Review!"
else:
  disp = "Negative Review!"

In [ ]:
disp

'Negative Review!'

In [ ]:
!pip install streamlit
!pip install pyngrok===4.1.1
from pyngrok import ngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 76.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 KB 20.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 KB 23.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.7/238.7 KB 25.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 83.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 KB 11.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 KB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 58.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.5/84.5 KB 12.2 MB/s eta 0:00:00
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19581 sha256=a56b35a0fa9ed84c9d8e1b511ac1b699c88e3ef21c32